default: lab1b-client lab1b-server

lab1b-client: lab1b-client.c
	gcc -o lab1b-client -Wall -Wextra lab1b-client.c

lab1b-server: lab1b-server.c
	gcc -o lab1b-server -Wall -Wextra lab1b-server.c

clean:
	rm -r lab1a-client lab1a-server
