# NAME: Ram Goli
# EMAIL: ramsgoli@gmail.com
# ID: 604751659

default: lab1a

lab1a: lab1a.c
	gcc -o lab1a -Wall -Wextra lab1a.c

dist:
	tar -czvf lab1a-604751659.tar.gz lab1a.c README Makefile

clean:
	rm -f lab1a lab1a-604751659.tar.gz
